### ISSUE TITLE
Moving to org

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ko.javascript.info#21]
Hello!

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by Violet-Bora-Lee** [comment]
Hello, Ilya.
I've got your mail and shared among contributors.
We've decided to choose the 1st option as we are tracking translation status in the [Google spreadsheet](https://docs.google.com/spreadsheets/d/1fYaEI8vz26N3R2VaxrlNnk9fMQ8zIy4RpvjRp4jZd0Q/edit#gid=0) mainly.
However, in order to merge all PR submitted until now, we need time to review the commits. I sent the message contributors that it is recommended to modify and revise PR until Wednesday Midnight, Korean TIme(GMT+9). I'll reply to your email after all merging PR around Wednesday.

**Comment by iliakan** [comment]
Transferring is actually a very simple process, maybe it could be easier for you ;)

**Comment by iliakan** [comment]
just contact github to unfork the repo, and then it's a few clicks.

**Comment by iliakan** [comment]
all issues and pr history remains

**Comment by Violet-Bora-Lee** [comment]
Oh, I see 👍  I'll contact Github soon.

**Comment by Violet-Bora-Lee** [comment]
Hello, I was trying to transfer this repo to the organization by following the way in the [Github Help page](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account). However, I couldn't because the permission is needed. 

I saw the message, "You don’t have the permission to create repositories on javascript-tutorial".

I'm looking forward to your agreement to transfer this repo.

**Comment by iliakan** [comment]
Transfer to @iliakan i’ll move along.
Thanks!

**Comment by Violet-Bora-Lee** [comment]
Done!

**Comment by iliakan** [comment]
Moved to org and added you as a maintainer.
- Merged latest changes from English.
- Created progress issue.
- Created new Readme, the previous translation is at `git show 48038acf:README.md`.

**Comment by iliakan** [comment]
Please merge back translation of Readme, I couldn't do it

**Comment by Violet-Bora-Lee** [comment]
got it!
